app:
  # 应用ID
  id: browser-server
# 指定环境
env: DEV
apollo:
  bootstrap:
    # 是否开启 Apollo
    enabled: true
    eagerLoad:
      # 开启后，Apollo的配置会先于logback的配置加载
      enable: true
      # 指定使用哪个 Namespace 的配置，默认 application
    namespaces: scan-agent-common,scan-agent-server-yml.yml
  # Apollo 配置中心地址，多个地址以逗号隔开
  # meta和env推荐使用VM参数指定 -Dapollo.configService=http://192.168.9.149:8080 -Denv=DEV
  # apollo.configService的优先级比apollo.meta高,configService会覆盖meta
  meta: http://192.168.9.149:8080
  # 配置本地配置缓存目录
  cacheDir: ./apolloCache/
#日志配置
logging:
  #日志级别
  level:
    org.springframework: error
    org.springframework.retry: error
    com.platon.browser: error
    com.platon.browser.bootstrap: error
    com.platon.browser.collection: error
    com.platon.browser.collection.queue.handler: error
    com.platon.browser.common: error
    com.platon.browser.complement: error
    com.platon.browser.complement.handler: error
    com.platon.browser.complement.converter: error
    com.platon.browser.persistence: error
    com.platon.browser.persistence.handler: error
    com.platon.browser.persistence.queue.handler: error
    com.platon.browser.task: error
  file:
    name: ./logs/scan-agent.log